name: Smoke Tests

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

jobs:
  SmokeTests_Chrome_Latest:
    name: Smoke Tests on Chrome Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Chrome Latest
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:latest

      - name: Run Smoke Tests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          
          mvn -q test -Dtest=UITests.SearchingTest#testSearchByCatKeyWord,UITests.FilteringTest#testFilterByColorRed

      - name: Tear Down Grid
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker stop grid_container || true
          docker rm grid_container || true
