name: UI Testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: 'Grid URL (default: http://localhost:4444)'
        default: 'http://localhost:4444'
      browser:
        required: true
        type: choice
        description: 'Select browser'
        options:
          - chrome
          - firefox
        default: 'chrome'

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Start Selenium Grid
        if: ${{ contains(inputs.grid_url, 'localhost') }}
        run: |
          docker run -d -p 4444:4444 --shm-size=2gb \
            -e SE_NODE_MAX_SESSIONS=4 \
            -e SE_NODE_OVERRIDE_MAX_SESSIONS=true \
            -e SE_START_XVFB=false \
            --name selenium-grid \
            selenium/standalone-${{ inputs.browser }}:latest
          
          # Wait for grid to be ready
          echo "Waiting for Grid to be ready..."
          timeout 60s bash -c 'while ! curl -sSL "http://localhost:4444/wd/hub/status" 2>&1 | grep -q "\"ready\": true"; do sleep 2; done'
          
          # Print grid logs for debugging
          docker logs selenium-grid

      - name: Print Environment Info
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn --version
          echo "Grid URL: ${{ inputs.grid_url }}"
          echo "Browser: ${{ inputs.browser }}"

      - name: Run Tests with Debug
        run: |
          export GRID_URL=${{ inputs.grid_url }}
          export BROWSER=${{ inputs.browser }}
          
          mvn test -X \
            -Dgrid.url=${GRID_URL} \
            -Dbrowser=${BROWSER} \
            -Dmaven.test.failure.ignore=true \
            -Dwebdriver.remote.quietExceptions=false

      - name: Print Grid Logs
        if: always() && contains(inputs.grid_url, 'localhost')
        run: docker logs selenium-grid

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/screenshots/

      - name: Stop Selenium Grid
        if: always() && contains(inputs.grid_url, 'localhost')
        run: docker stop selenium-grid || true