name: UI testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean

      firefox_133_0:
        description: 'Firefox (133.0)'
        required: false
        type: boolean

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Launch standalone grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Run Tests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          
          mvn test -Dtest=UITests.*
          
          # Tear down grid if exists
          docker stop grid_container || true
          docker rm grid_container || true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Chrome Test Results
          path: target/surefire-reports/

  TestFirefox_133_0:
    name: Test Firefox 133.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.firefox_133_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Launch standalone grid - Firefox
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-firefox:133.0-geckodriver-0.35-grid-4.27.0-20250101

      - name: Run Tests
        run: |
          export BROWSER=firefox
          export GRID_URL=${{ github.event.inputs.grid_url }}
          
          mvn test -Dtest=UITests.*
          
          # Tear down grid if exists
          docker stop grid_container || true
          docker rm grid_container || true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Firefox Test Results
          path: target/surefire-reports/
