name: UI Testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444
      browser:
        description: 'Select Browser'
        required: true
        type: choice
        options:
          - chrome
          - firefox
        default: 'chrome'

jobs:
  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Setup Chrome
        if: ${{ inputs.browser == 'chrome' }}
        run: |
          docker run --name selenium-hub -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:4.27.0

      - name: Setup Firefox
        if: ${{ inputs.browser == 'firefox' }}
        run: |
          docker run --name selenium-hub -d -p 4444:4444 --shm-size=2gb selenium/standalone-firefox:4.27.0

      - name: Wait for Selenium Grid
        run: |
          echo "Waiting for Selenium Grid to be ready..."
          timeout 30 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4444/wd/hub/status)" != "200" ]]; do sleep 2; done' || false

      - name: Run UI Tests
        run: |
          mvn test -Dtest=UITests.** -Dbrowser=${{ inputs.browser }} -Dgrid.url=${{ inputs.grid_url }}
        env:
          MAVEN_OPTS: "-Xmx2048m"

      - name: Capture Selenium Logs
        if: always()
        run: |
          docker logs selenium-hub

      - name: Stop Selenium Grid
        if: always()
        run: |
          docker stop selenium-hub
          docker rm selenium-hub

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 7